clearMagazineCargoGlobal _this;
clearItemCargoGlobal _this;
clearWeaponCargoGlobal _this;
clearBackpackCargoGlobal _this;
_this addMagazineCargo ["rhs_mag_an_m8hc", 15];
_this addMagazineCargo ["rhs_mag_m67", 15];
_this addMagazineCargo ["rhs_mag_M441_HE", 10];
_this addMagazineCargo ["rhs_mag_30Rnd_556x45_Mk318_Stanag", 40];
_this addMagazineCargo ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 20];
_this addMagazineCargo ["rhsusf_20Rnd_762x51_m118_special_Mag", 10];
_this addMagazineCargo ["rhs_200rnd_556x45_M_SAW", 4];
_this addMagazineCargo ["rhsusf_mag_7x45acp_MHP", 20];
_this addMagazineCargo ["rhs_fgm148_magazine_AT", 1];
_this addMagazineCargo ["rhsusf_mag_10Rnd_STD_50BMG_mk211", 20];
_this addMagazineCargo ["Item_FirstAidKit", 50];
Signal = "SmokeShellGreen" createVehicle position _this;
